# Generated by Django 6.0.2 on 2026-02-07 10:45

import application.models.applicant
import application.models.application
import application.models.document
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_ID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('employer', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_start_date', models.DateField()),
                ('credit_score', models.IntegerField()),
                ('income', models.FloatField()),
                ('savings', models.FloatField()),
                ('expected_movein_date', models.DateField()),
                ('reason', models.TextField()),
                ('has_rented_before', models.BooleanField(default=False)),
                ('rental_history', models.JSONField(blank=True, null=True, validators=[application.models.applicant.rental_history])),
                ('marital_status', models.BooleanField()),
                ('children', models.BooleanField(default=False)),
                ('emergency_info', models.JSONField(validators=[application.models.applicant.emergency_info])),
            ],
            options={
                'indexes': [models.Index(fields=['profile_ID'], name='application_profile_cb45e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.JSONField(blank=True, null=True, validators=[application.models.document.required_documents])),
                ('file_field', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('applicant_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='application.applicant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_ID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('building_ID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('submitted_at_date', models.DateField()),
                ('lease_term', models.CharField(max_length=200)),
                ('resident_info', models.JSONField(validators=[application.models.application.resident_info])),
                ('application_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('applicant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='application.applicant')),
            ],
            options={
                'indexes': [models.Index(fields=['unit_ID'], name='application_unit_ID_0dd8ef_idx'), models.Index(fields=['building_ID'], name='application_buildin_66672f_idx')],
            },
        ),
    ]
