# Generated by Django 6.0.2 on 2026-02-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Advice',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='Cons',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='Pros',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='Title',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='deposit_withheld',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='ending_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='full_address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='starting_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='total_deposit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='unit_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
