# Generated by Django 6.0.2 on 2026-02-07 09:52

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_ID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('building_ID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('full_address', models.TextField()),
                ('review_date', models.DateTimeField()),
                ('cleanliness_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('garbage_management_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('neighbours_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('water_supply_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('building_maintenance_rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('Title', models.TextField()),
                ('Pros', models.TextField()),
                ('Cons', models.TextField()),
                ('Advice', models.TextField()),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField()),
                ('is_received_deposit', models.BooleanField(default=False)),
                ('total_deposit', models.FloatField()),
                ('deposit_withheld', models.FloatField()),
                ('is_pet_friendly', models.BooleanField(default=False)),
                ('starting_rent', models.FloatField()),
                ('ending_rent', models.FloatField()),
                ('unit_no', models.CharField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('INPROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['profile_ID'], name='reviews_rev_profile_89488b_idx'), models.Index(fields=['building_ID'], name='reviews_rev_buildin_a8eb33_idx')],
            },
        ),
    ]
