# Generated by Django 6.0.2 on 2026-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='expected_movein_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='marital_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='savings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_at_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
